# Generated by Django 5.1.7 on 2025-03-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('año_lanzamiento', models.IntegerField(verbose_name='Año de Lanzamiento')),
                ('genero', models.CharField(choices=[('ACC', 'Acción'), ('COM', 'Comedia'), ('DRM', 'Drama'), ('TER', 'Terror'), ('SCI', 'Ciencia Ficción'), ('ANM', 'Animación'), ('AVT', 'Aventura'), ('FAN', 'Fantasía'), ('DOC', 'Documental'), ('OTH', 'Otro')], max_length=3, verbose_name='Género')),
                ('duracion', models.IntegerField(verbose_name='Duración (minutos)')),
                ('director', models.CharField(max_length=255, verbose_name='Director')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='peliculas/', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Película',
                'verbose_name_plural': 'Películas',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
